version: '3.4'

# Default configuration for apps with GUI support
x-gui-app:
  &default-gui-app
  network_mode: "host"
  user: ${user_uid}
  environment:
  - location=${PWD}
  - DISPLAY
  - EPICS_CA_ADDR_LIST=172.17.255.255
  - EPICS_CA_MAX_ARRAY_BYTES=80000000
  security_opt:
  - "apparmor=docker-smurf"
  tty: true
  stdin_open: true

services:
  smurf_server_s%%SLOT_NUMBER%%:
    <<: *default-gui-app
    image: tidair/pysmurf-server-base:%%SERVER_VERSION%%
    container_name: smurf_server_s%%SLOT_NUMBER%%
    volumes:
    - /data:/data
    - /home/${user_name}:/home/${user_name}
    - ${PWD}/fw:/tmp/fw
    - ${PWD}/rogue:/usr/local/src/rogue
    - ${PWD}/pysmurf:/usr/local/src/pysmurf
    command: -g -w smurf_server_s%%SLOT_NUMBER%% -S shm-smrf-sp01 -N %%SLOT_NUMBER%% -e smurf_server_s%%SLOT_NUMBER%% %%COMM_ARGS%% -d /tmp/fw/config/defaults.yml ${extra_opts}
    #entrypoint: bash
    logging:
      options:
        tag: smurf_server
  pysmurf_s%%SLOT_NUMBER%%:
    <<: *default-gui-app
    image: tidair/pysmurf-client:%%CLIENT_VERSION%%
    container_name: pysmurf_s%%SLOT_NUMBER%%
    volumes:
    - /data:/data
    - /home/${user_name}:/home/${user_name}
    - ${PWD}/pysmurf:/usr/local/src/pysmurf
    command: --epics smurf_server_s%%SLOT_NUMBER%%
    logging:
      options:
        tag: pysmurf
    depends_on:
    - smurf_server_s%%SLOT_NUMBER%%