# Add label 'docker-script' to any change within
# 'docker_scripts' folder or any subfolders
docker-scripts:
  - docker_scripts/**/*

# Add label 'server-scripts' to any change within
# 'server_scripts' folder or any subfolders
server-scripts:
  - server_scripts/**/*