os: linux

dist: bionic

language: node_js

node_js:
  - 8

stages:
  - name: generate_release_notes
    if: tag IS present

jobs:
  include:
    - stage: generate_release_notes
      name: "Generate Release Notes"
      before_script:
        - npm install github-release-notes -g
      script:
        - gren release
